image: python:3.8

stages:
  - test

package_installation:
  stage: test
  tags:
    - docker
  script:
    - pip3 install tox pytest ansible
    - echo $CI_COMMIT_MESSAGE
    - tox
    - cd ansible
    - ansible-playbook playbook.yml
