{
 "title": "Time Series Monitoring Dashboard",
 "description": "Dashboad displaying job queue metrics for Slurm and TORQUE schedulers",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Squeue  COMPLETING Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"COMPLETING\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue SUSPENDED Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"SUSPENDED\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue RUNNING Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"RUNNING\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue PENDING Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"PENDING\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue COMPLETED Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"COMPLETED\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue TIME_OUT Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"TIME_OUT\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue CANCELLED Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"CANCELLED\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue PRE_EMPTED Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"PRE_EMPTED\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue CONFIGURING Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"CONFIGURING\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue FAILED Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"FAILED\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  },
  {
   "title": "Squeue NODE_FAIL Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "squeue_jobs{job_type=\"NODE_FAIL\"}",
     "legendFormat": "{{slurm_group}}"
    }
   ]
  }
 ]
}