- name: 'Download latest version of Grafana'
  apt: 
    deb: https://dl.grafana.com/oss/release/grafana_7.1.3_amd64.deb 

- name: 'Install packages'
  apt: pkg={{ item }} state=latest
  with_items:
  - adduser
  - libfontconfig

- name: 'Configure grafana.ini for nginx revrse proxy'
  copy:
    src: files/grafana.ini
    dest: /etc/grafana/

- name: 'Start Grafana daemon'
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: grafana-server

- name: Remove file (delete file)
  file:
    path: grafana_latest_amd64.deb
    state: absent
