- name: 'Download latest version of Grafana'
  apt: 
    deb: https://dl.grafana.com/oss/release/grafana_7.1.3_amd64.deb 

- name: 'Install packages'
  apt: pkg={{ item }} state=latest
  with_items:
  - adduser
  - libfontconfig

- name: 'Install community.grafana'
  shell:
    cmd: ansible-galaxy collection install community.grafana

- name: 'Start Grafana daemon'
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: grafana-server

- name: Remove file (delete file)
  file:
    path: grafana_latest_amd64.deb
    state: absent

- name: 'Create Prometheus datasource'
  grafana_datasource:
    name: 'datasource-prometheus'
    grafana_url: 'http://localhost:3000'
    grafana_user: 'admin'
    grafana_password: 'admin'
    ds_type: 'prometheus'
    is_default: 'yes'
    ds_url: 'http://localhost:9090'
    state: present

- name: 'Import Grafana dashboard'
  collections:
    - community.grafana
  grafana_dashboard:
    grafana_url: 'http://localhost:3000'
    grafana_user: 'admin'
    grafana_password: 'admin'
    path: '/home/cathal/Documents/cathal/ansible/roles/grafana/files/dashboards/grafana.json'
    commit_message: 'Update by Ansible'
    state: present
    overwrite: true
