global:
  scrape_interval: 15s

#rule_files:
#  - 'prometheus.rules.yml'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:19090']

  - job_name: 'slurm_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'grafana'
    scrape_interval: 5s
    metrics_path: /grafana/metrics
    static_configs:
      - targets: ['localhost:80']

#alerting:
  #alertmanagers:
  #- static_configs:
  #  - targets:
  #    - localhost:9093
