global:
  resolve_timeout: 1m

route:
  receiver: slack-notifications

receivers:
- name: email-me
  email_configs:
  - to: cathalcorbett3@gmail.com
    from: cathalcorbett3@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: '<email_address>@gmail.com'
    auth_identity: '<email_address>@gmail.com'
    auth_password: '*************************'
    send_resolved: true
- name: slack-notifications
  slack_configs:
  - api_url: '<slack_url>'
    channel: '#<channell_name>'
    send_resolved: true
