route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: cathalcorbett3@gmail.com
    from: cathalcorbett3@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: 'cathalcorbett3@gmail.com'
    auth_identity: 'cathalcorbett3@gmail.com'
    auth_password: 'xxxxxxxxxx'
