- name: 'Install  package nginx'
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: 'Copy reverse proxy config settings'
  blockinfile: path=/etc/nginx/sites-available/default block={{lookup('file', 'files/default')}} create=yes state=present

- name: 'Start nginx daemon'
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: nginx
