- name: 'Install  package nginx'
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: 'Copy reverse proxy config settings'
  copy:
    src: files/default
    dest: /etc/nginx/sites-available/default

- name: 'Start nginx daemon'
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: nginx
