- name: 'Install packages'
  apt: pkg=curl state=latest

- name: 'Add Prometheus User'
  user:
    name: prometheus
    create_home: no
    shell: '/bin/false'
    comment: 'Prometheus User'
    password: '!'

- name: 'Make directories and dummy files necessary for prometheus'
  file:
    path: '{{ item }}'
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /etc/alertmanager

- name: 'Make directories and dummy files necessary for prometheus'
  file:
    path: '{{ item }}'
    state: touch
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus/prometheus.yml
    - /etc/prometheus/prometheus.rules.yml
    - /etc/alertmanager/alertmanager.yml

- name: 'Download & Install & Configure latest Prometheus version'
  script: files/prometheus.sh

- name: 'Assign ownership of prometheus tools to prometheus user'
  file:
    path: '{{ item }}'
    owner: prometheus
    group: prometheus
    mode: a+x
  with_items:
    - /usr/local/bin/prometheus
    - /usr/local/bin/promtool

- name: 'Assign ownership of prometheus tools to prometheus user'
  file:
    path: '{{ item }}'
    state: directory
    owner: prometheus
    group: prometheus
    recurse: yes
    mode: a+x
  with_items:
    - /etc/prometheus/consoles
    - /etc/prometheus/console_libraries

- name: 'Populate prometheus.yml file'
  copy:
    src: files/prometheus/prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: 'Populate prometheus.rules.yml file'
  copy:
    src: files/prometheus/prometheus.rules.yml
    dest: /etc/prometheus/prometheus.rules.yml

- name: 'Populate prometheus.service file'
  copy:
    src: files/prometheus/prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: 'Populate alertmanager.yml file'
  copy:
    src: files/alertmanager/alertmanager.yml
    dest: /etc/alertmanager/alertmanager.yml

- name: 'Populate alertmanager.service file'
  copy:
    src: files/alertmanager/alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: 'Start HPC Exporter daemon'
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: '{{ item }}'
  with_items:
    - prometheus
    - alertmanager

- name: 'Remove files'
  shell: '{{ item }}'
  with_items:
    - rm -rf prometheus-*
    - rm -rf alertmanager-*
