- name: 'Install Packages'
  apt: pkg=python3-pip state=latest

- name: 'Download Prometheus Client'
  pip:
    name: prometheus_client
    state: latest
    executable: pip3

- name: 'Install Job Queue Scheduler Prometheus Exporter'
  pip:
    name: job-queue-exporter
    state: latest
    executable: pip3

- name: 'Add HPC Prometheus Exporter User'
  user:
    name: hpc-exporter
    create_home: no
    shell: '/bin/false'
    comment: 'HPC Prometheus Exporter User'
    password: '!'

- name: 'Assign ownership of hpc-exporter tools to hpc-exporter user'
  file:
    path: '{{ item }}'
    state: directory
    owner: hpc-exporter
    group: hpc-exporter
    recurse: yes
    mode: a+x
  with_items:
    - /etc/hpc-exporter
    - /var/lib/hpc-exporter  

- name: 'Change ownership of python scripts'
  file:
    path: '{{ item }}'
    owner: hpc-exporter
    group: hpc-exporter
    state: file
    mode: a+x
  with_items:
      - /usr/local/bin/main_exporter
      - /usr/local/bin/squeue_dummy

- name: 'Populate configuration files'
  copy:
    src: files/hpc-exporter.service
    dest: /etc/systemd/system/

- name: 'Start HPC Exporter daemon'
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: hpc-exporter
